// Перевод жанров с английского на русский
export const GENRE_TRANSLATIONS: Record<string, string> = {
  'Action': 'Экшен',
  'Adventure': 'Приключения',
  'Comedy': 'Комедия',
  'Drama': 'Драма',
  'Fantasy': 'Фэнтези',
  'Horror': 'Хоррор',
  'Mecha': 'Меха',
  'Music': 'Музыка',
  'Mystery': 'Мистика',
  'Psychological': 'Психология',
  'Romance': 'Романтика',
  'Sci-Fi': 'Научная фантастика',
  'Slice of Life': 'Повседневность',
  'Sports': 'Спорт',
  'Supernatural': 'Сверхъестественное',
  'Thriller': 'Триллер',
  'Animation': 'Анимация',
  'Award Winning': 'Награжденное',
  'Boys Love': 'Бойз Лав',
  'Girls Love': 'Гёрлс Лав',
  'Gourmet': 'Гурман',
  'Isekai': 'Исекай',
  'Suspense': 'Саспенс',
  'Avant Garde': 'Авангард',
  'Ecchi': 'Эччи',
  'Erotica': 'Эротика',
  'Hentai': 'Хентай',
  'Mahou Shoujo': 'Магическая девушка',
  'Mahou Shounen': 'Магический парень',
  'Parody': 'Пародия',
  'Samurai': 'Самураи',
  'Shoujo': 'Сёдзё',
  'Shounen': 'Сёнен',
  'Space': 'Космос',
  'Vampire': 'Вампиры',
  'Yaoi': 'Яой',
  'Yuri': 'Юри',
  'Kids': 'Детское',
  'Cars': 'Машины',
  'Dementia': 'Деменция',
  'Game': 'Игры',
  'Military': 'Военное',
  'Police': 'Полиция',
  'Super Power': 'Суперспособности',
  'Demons': 'Демоны',
  'Historical': 'Историческое',
  'Martial Arts': 'Боевые искусства',
  'School': 'Школа',
  'Seinen': 'Сейнен',
  'Josei': 'Дзёсей',
  'Harem': 'Гарем',
  'Magic': 'Магия',
  'Visual Arts': 'Визуальное искусство',
  'Workplace': 'Рабочее место',
  'Reincarnation': 'Реинкарнация',
  'Reverse Harem': 'Обратный гарем',
  'Time Travel': 'Путешествие во времени',
  'Video Game': 'Видеоигры',
  'Cyberpunk': 'Киберпанк',
  'Steampunk': 'Стимпанк',
  'Post-Apocalyptic': 'Постапокалипсис',
  'Zombies': 'Зомби',
  'Aliens': 'Инопланетяне',
  'Robots': 'Роботы',
  'Survival': 'Выживание',
  'Tragedy': 'Трагедия',
  'Wuxia': 'Уся',
  'Xianxia': 'Сянься',
  'Iyashikei': 'Исекай (лечебное)',
  'Chibi': 'Чиби',
  'CGDCT': 'Милые девочки',
  'Anthology': 'Антология',
  'Crossdressing': 'Кросдрессинг',
  'Delinquents': 'Хулиганы',
  'Gag Humor': 'Гэг-юмор',
  'High Stakes Games': 'Игры с высокими ставками',
  'Idols': 'Айдолы',
  'Love Polygon': 'Любовный многоугольник',
  'Otaku Culture': 'Отаку культура',
  'Showbiz': 'Шоубизнес',
  'Strategy Game': 'Стратегическая игра',
  'Tournament': 'Турнир',
  'Urban Fantasy': 'Городское фэнтези',
  'Villainess': 'Злодейка',
  'Virtual Reality': 'Виртуальная реальность',
  'Childcare': 'Уход за детьми',
  'Cooking': 'Готовка',
  'Detective': 'Детектив',
  'Educational': 'Образовательное',
  'Family': 'Семейное',
  'Medical': 'Медицинское',
  'Organized Crime': 'Организованная преступность',
  'Performing Arts': 'Сценическое искусство',
  'Racing': 'Гонки',
  'Showbiz': 'Шоубизнес',
  'Team Sports': 'Командный спорт',
  'Traditional Games': 'Традиционные игры',
}

export function translateGenre(genre: string): string {
  return GENRE_TRANSLATIONS[genre] || genre
}

export function translateGenres(genres: string[]): string[] {
  return genres.map(translateGenre)
}
